### ISSUE TITLE
Feature request SmartCrop

### ISSUE THREAD

**Issue by khuezy** [milliHQ/terraform-aws-next-js-image-optimization#125]
Hi, this works great but I'm wondering if smartcrop can be applied in the optimization.

eg:
https://github.com/jwagner/smartcrop-sharp
https://github.com/jwagner/smartcrop.js

**Comment by ofhouse** [comment]
This would only possible with implementing some unstable hacks, since the sharp implementation is imported inside the Next.js optimizer:
https://github.com/vercel/next.js/blob/a9d6d9f71acb17a92a3c0965df342049c0dec115/packages/next/server/image-optimizer.ts#L42

However I think this is out of scope of this project, since we aim to be fully compatible with the Next.js feature set.
Therefore adding features that are not part of Next.js could be hard to maintain.

Would suggest to vote for the appropriate feature request on the Next.js project instead: https://github.com/vercel/next.js/discussions/18871

The image optimization API in Next.js is still early in its development, so I guess the chances are not too bad that more options for layout will be added.

**Comment by khuezy** [comment]
I see, thank you.
