### ISSUE TITLE
Question about Denial-of-Service (DoS)

### ISSUE THREAD

**Issue by MrHertal** [milliHQ/terraform-aws-next-js-image-optimization#75]
Hi 👋 

First of all, thank you for this nice project. Code is very clean and inspiring.

I am considering using it in production and I have a question regarding DoS attack.
I think image optimization could be expensive if a bad person plays with the api endpoint.

My first question is: every time you get a `Miss from cloudfront`, the lambda is run and (costly) image optimization occurs?

If it's the case, the api should be less permissive than it is. I noticed that with the api gateway configuration: `/_next/{proxy+}`, you just have to put random strings like `/_next/blabla` to avoid cache (Miss) and generate a new image.

What are your thoughts about this?

Thanks!

**Comment by ofhouse** [comment]
Hi, thanks for raising the question.

A `Miss from cloudfront` indicates that the object is not available at the edge cache and is requested from the origin.
The origin itself is also wrapped in a cache layer ([CloudFront Origin Shield](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/origin-shield.html)), so when two identical requests from different locations (e.g. Frankfurt and Paris) are made, the first request is forwarded to the Lambda while the second is served from the Origin Shield cache layer without hitting the Lambda.
So there is a "soft miss" (served from Origin Shield) and a "hard miss" (processed by Lambda) which are both labeled with `Miss from cloudfront`.

Yes, the configuration of the API-Gateway with the route `/_next/{proxy+}` would enable an attack scenario as you described since the path could be altered with each request to prevent a caching in both layers.
To mitigate the issue the routes accepted by API-Gateway should be restricted to `/_next/image` & `/_next/image/`.

However the issue would still be present then, since the attack could be modified to target other parts of the cache-key from CloudFront.
The cache-key is currently composed of the path, different request headers [`"accept", "referer"`](https://github.com/milliHQ/terraform-aws-next-js-image-optimization/blob/main/main.tf#L142) and the path parameters [`"url", "w", "q"`](https://github.com/milliHQ/terraform-aws-next-js-image-optimization/blob/main/main.tf#L139).
So modifying the `accept` or `referer` headers in the client request would also result in a Miss from CloudFront. 

However CloudFront has several monitoring and security measurements built-in to mitigate DoS attacks and can be further secured with [AWS WAF](https://aws.amazon.com/waf/).

So while I agree that we should restrict the path further in API Gateway, I would say that CloudFront is not an easy target for a massive DoS attack.

**Comment by MrHertal** [comment]
Hi, thanks for the detailed explanation!

Let's say that I'm in a situation where I want to restrict the api as much as I can before relying on AWS built in protection or WAF.

If I understand correctly, here are the settings that compose the cache-key:

- `accept` header

Values could be limited to the [browsers default](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values#values_for_an_image) so that an attacker could not set random values.

- `referer` header

I don't understand why the referer is part of the cache-key because I could use the same api on multiple next.js website.

- `w` and `q` parameters

Possible values are limited.

- `url` parameter

The value is reliable since url domain is white listed. But an attacker could add query params to that url. A solution for that case would be to only allow urls without query params.

Sorry if it's beyond the scope of this library and if it's specific to my use case.

Do you think that such restrictions would effectively protect the api and avoid useless costs ?

**Comment by ofhouse** [comment]
Absolutely would welcome a PR on this!

My current plan is to start small and implement the changes to the `referer` header first.
Since it's not that much time until Next.js 12 will be released (Currently scheduled for 26. Oct in time with Next.js Conf) and we plan to release new versions timely after new Next.js releases I would defer the other proposed changes to upcoming releases.

**Comment by ofhouse** [comment]
Closing this for now since I've splitted the issue in smaller packages:
- **Referer header**: #87
- **Accept header**: #88
- **url parameter**: #89

Thanks for the input!
